### ISSUE TITLE
Add Match to Option

### ISSUE THREAD

**Issue by cameronpresley** [cameronpresley/Optionally#25]
When working with Options, you'll eventually need to eventually leave the Option context near the boundary and work on the value directly. 

As it stands now, the only way to get the value is to use `Do` and a mutable variable. 

Suggested feature is to add a method called Match that satisfies the following

```
var some = Option.Some(4)
var none = Option.No<int>()
int result = some.Match(() => return 0, x => return x); // would yield 4
int result = none.Match(() => return 0, x => return x); // would yield 0
```

**Comment by zaudtke** [comment]
#26 Pull request sent

**Comment by cameronpresley** [comment]
Awesome work @zaudtke, thanks!
